version: '3.8'

services:
  wetalk-be:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev.be
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  wetalk-fe:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev.fe
    ports:
      - "3000:3000"
    depends_on:
      - wetalk-be

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: exampleuser
      MONGO_INITDB_ROOT_PASSWORD: examplepass
    volumes:
      - mongo-data:/data/db  # Persistent storage for MongoDB


volumes:
  mongo-data:  # Volume for MongoDB to persist data
