FROM node:16-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./frontend/package.json  ./frontend


RUN npm install:combined

COPY . .

RUN npm run build


EXPOSE 8080

CMD ["npm", "start"]