name: Wetalk Backend CI/CD

on:
    push:
        branches:
        - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push docker to dockerhub
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: kunalnasa/wetalk-backend:${{ github.sha }}

            # - name: Deploy to EC2
            #   run: |
            #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
            #     chmod 600 ~/ssh_key

            #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.110.45.173 << 'EOF'
            #       # Stop and remove any existing container
            #       sudo docker stop wetalk-backend || true
            #       sudo docker rm wetalk-backend || true

            #       # Pull the latest image
            #       sudo docker pull kunalnasa/wetalk-backend:${{ github.sha }}

            #       # Run the new container 
            #       sudo docker run --name wetalk-backend -d -p 8080:8080 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" kunalnasa/wetalk-backend:${{ github.sha }}
            #     EOF
