name: Wetalk Frontend CI/CD

on:
    push:
        branches:
        - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push docker to dockerhub
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.frontend
                push: true
                tags: kunalnasa/wetalk-frontend:${{ github.sha }}
